logLevel = 3
identd = false
gateway_name = "kiwi-expo"
send_quit_on_client_close = "Client closed"

[clients]

[server.1]
bind = "0.0.0.0"
port = 7779

[fileserving]
enabled = true
webroot = www/

[transports]
websocket
kiwiirc

[allowed_origins]

[reverse_proxies]
192.168.0.0/16
172.16.0.0/12
10.0.0.0/8
127.0.0.0/8

[upstream.1]
hostname = "192.168.22.27"
port = 6668
tls = false
timeout = 10
throttle = 2
